env:
  browser: true
  commonjs: true
  es6: true
extends: 
  - eslint:recommended
  - plugin:react/recommended
globals:
  PUBLIC_PATH: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  no-console: 1
  no-unused-vars: 1
  react/display-name: 0
  react/prop-types: 0
  '@typescript-eslint/no-non-null-assertion': 0
  '@typescript-eslint/no-non-null-asserted-optional-chain': 0